creation_rules:
  # ONLY credentials carry secrets → only they get encrypted.
  # vcenter.tfvars = inventory (datacenter/datastore/network) → plaintext, readable.
  - path_regex: secure/.*/credentials\.tfvars$
    age: age1gka0npw4cldxsv5hfsqj23d94y846qzur9xlq8kds0xeehu5cajs8hnm30

  - path_regex: \.tmp-sops-plain/.*/credentials\.tfvars$
    age: age1gka0npw4cldxsv5hfsqj23d94y846qzur9xlq8kds0xeehu5cajs8hnm30
