AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create S3 bucket and DynamoDB table for Terraform remote state'
Resources:
  TerraformStateBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      VersioningConfiguration:
        Status: Enabled

  TerraformStateLockTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  BucketName:
    Value: !Ref TerraformStateBucket
  LockTableName:
    Value: !Ref TerraformStateLockTable
